# Generated by Django 5.0.6 on 2024-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NestGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao1', models.TextField(max_length=1500)),
                ('descricao2', models.TextField(max_length=1500)),
                ('descricao3', models.TextField(max_length=1500)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
