# Generated by Django 5.0.6 on 2024-06-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoNestGuard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nestguard',
            old_name='logo',
            new_name='logoGrandeClaro',
        ),
        migrations.AddField(
            model_name='nestguard',
            name='logoGrandeEscuro',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nestguard',
            name='logoNavbarClaro',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nestguard',
            name='logoNavbarEscuro',
            field=models.ImageField(default=1, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
