# Generated by Django 5.0.6 on 2024-06-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoNestGuard', '0003_nestguard_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestguard',
            name='logo',
        ),
    ]
