# Generated by Django 5.0.6 on 2024-06-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacaoNestGuard', '0004_remove_nestguard_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestguard',
            name='logoGrandeClaro',
            field=models.ImageField(upload_to='logoGrandeClaro/'),
        ),
        migrations.AlterField(
            model_name='nestguard',
            name='logoGrandeEscuro',
            field=models.ImageField(upload_to='logoGrandeEscuro/'),
        ),
        migrations.AlterField(
            model_name='nestguard',
            name='logoNavbarClaro',
            field=models.ImageField(upload_to='logoNavbarClaro/'),
        ),
        migrations.AlterField(
            model_name='nestguard',
            name='logoNavbarEscuro',
            field=models.ImageField(upload_to='logoNavbarEscuro/'),
        ),
    ]
